basic_settings:
  site_title: R H Works
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/rhworks.png
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/'
    - title: 'Information'
      url: '/info'

footer_settings:
  logo_image: /images/rhworks2.png
  logo_width: 50
  footer_tagline: R H Works is a design and art direction studio

grid_settings:
  overlay_opacity: 1
  grid_spacing: 70

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#ffffff'
  text_light_color: '#ffffff'
  accent_color: '#00f'
  border_color: '#f4f5f6'
  overlay_background_color: '#00f'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500" rel="stylesheet">'
  title_font: '"Work Sans", sans-serif'
  body_font: '"Work Sans", sans-serif'
  regular_weight: 400
  bold_weight: 500
  site_title:
    small_size: 28
    medium_size: 34
    large_size: 40
    weight: 500
    letter_spacing: 0
  menu:
    small_size: 28
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
  grid_item_title:
    small_size: 20
    medium_size: 24
    large_size: 28
    weight: 500
    letter_spacing: 0
  grid_item_subtitle:
    small_size: 20
    medium_size: 24
    large_size: 28
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 28
    medium_size: 34
    large_size: 40
    weight: 400
    letter_spacing: 0
    line_height: 1.25
  h2:
    small_size: 20
    medium_size: 24
    large_size: 28
    weight: 500
    letter_spacing: 0
    line_height: 1.25
  h3:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.25
  h4:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  h5:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  h6:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  blockquote:
    small_size: 20
    medium_size: 24
    large_size: 28
    weight: 400
    letter_spacing: 0
    line_height: 1.25
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: '<meta name="google-site-verification" content="9i3soLM-bGG5ixcdT-IWBmRx5gen0wivw6SXlnOVyH8" />'
  custom_styles: ''
  header_js: ''
  footer_js: ''